# Generated by Django 3.0.5 on 2020-05-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.TextField(max_length=300)),
                ('murl', models.URLField()),
                ('mimg', models.URLField()),
                ('mduration', models.CharField(max_length=300)),
                ('mimdb', models.IntegerField()),
                ('mplot', models.TextField()),
                ('mdirectors', models.TextField()),
                ('mactors', models.TextField()),
                ('mgenres', models.TextField()),
                ('mlanguage', models.CharField(max_length=200)),
            ],
        ),
    ]
