# Generated by Django 3.0.5 on 2020-05-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mimdb',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
