# Generated by Django 3.0.5 on 2020-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0002_auto_20200503_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mimdb',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
